# .github/actions/custom-docker-build/action.yml

name: "Custom Docker Build, Test, and Push Action"
description: "Builds a Docker image, runs tests, and pushes the image. Takes image tag and version as inputs."

inputs:
  docker_username:
    description: "Docker User Account"
    required: true
  docker_password:
    description: "Docker User Access Token"
    required: true
  image_name:
    description: "Docker image 이름 (예: ryankor/devops-sparta)"
    required: true
  image_tag:
    description: "Docker image 태그 (예: 0.0.1)"
    required: true
  contexts:
    description: "Docker build context"
    required: true
  file:
    description: "Docker build file location"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }} 
        password: ${{ inputs.docker_password }}

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: false
        tags: ${{ inputs.image_name }}:${{ inputs.image_tag }}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Container Test
      run: |
        docker run -d --name test-container -p 8000:8000 ${{ inputs.image_name }}:${{ inputs.image_tag }}
        sleep 3
        curl -f http://localhost:8000 || exit 1
        docker stop test-container
        docker rm test-container
      shell: bash   # ← 이 부분이 추가됨

    - name: Push Docker Image
      run: |
        docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
      shell: bash   # ← 이 부분도 추가됨

